---

- name: Create user {{ raspi_config_replace_user['name'] }}
  user:
    name: "{{ raspi_config_replace_user['name'] }}"
    group: "{{ raspi_config_replace_user['name'] }}"
    groups: "sudo"
    state: present

- name: Add your login key to {{ raspi_config_replace_user['name'] }}
  authorized_key:
    user: "{{ raspi_config_replace_user['name'] }}"
    key: "{{ lookup('file', raspi_config_replace_user['path_to_ssh_key']) }}"

- name: Add {{ raspi_config_replace_user['name'] }} to sudoers
  lineinfile:
  args:
    dest: "/etc/sudoers.d/{{ raspi_config_replace_user['name'] }}"
    line:   "{{ raspi_config_replace_user['name'] }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    create: yes
    owner: root
    group: root
    mode: 640
